package selfhost

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/LaH-DeV/veles/lexer"
)

var update = flag.Bool("update", false, "rewrite selfhost/lexer/tables.vs from the Go lexer's character classes")

// TestUnicodeTables keeps selfhost/lexer/tables.vs equal to what the Go
// lexer decides for every character above ASCII: which start an identifier
// (UAX #31 ID_Start), which continue one (ID_Continue), and which it calls
// invisible in a diagnostic. The tables come from Go's unicode package, so a
// Go release with a newer Unicode moves both lexers at once: run
// `go test ./selfhost -run UnicodeTables -update`.
func TestUnicodeTables(t *testing.T) {
	var b strings.Builder
	b.WriteString("// Generated by selfhost/tables_test.go from the compiler's character\n")
	b.WriteString("// classes; do not edit. Regenerate with\n")
	b.WriteString("// `go test ./selfhost -run UnicodeTables -update`.\n")
	b.WriteString("//\n")
	b.WriteString("// Each table is the characters above ASCII in a class, as inclusive\n")
	b.WriteString("// (first, last) ranges in order.\n")
	table(&b, "ID_START", "UAX #31 ID_Start: the characters an identifier may begin with", lexer.IsIDStart)
	table(&b, "ID_CONTINUE", "UAX #31 ID_Continue: the characters an identifier may go on with", lexer.IsIDContinue)
	table(&b, "INVISIBLE", "format characters (Cf) and separators (Zs, Zl, Zp): what a diagnostic calls invisible", lexer.IsInvisible)
	table(&b, "PRINT", "the printable characters — letters, marks, numbers, punctuation, symbols — which `quote` writes as themselves", strconv.IsPrint)
	got := b.String()
	const path = "lexer/tables.vs"
	if *update {
		if err := os.MkdirAll("lexer", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (create it with -update)", err)
	}
	if strings.ReplaceAll(string(want), "\r\n", "\n") != got {
		t.Fatalf("%s is out of date: go test ./selfhost -run UnicodeTables -update", path)
	}
}

func table(b *strings.Builder, name, doc string, in func(rune) bool) {
	fmt.Fprintf(b, "\n/// %s.\npublic const %s: List<(i64, i64)> = [\n", doc, name)
	for r := rune(utf8.RuneSelf); r <= utf8.MaxRune; r++ {
		if !in(r) {
			continue
		}
		first := r
		for r+1 <= utf8.MaxRune && in(r+1) {
			r++
		}
		fmt.Fprintf(b, "  (0x%X, 0x%X),\n", first, r)
	}
	b.WriteString("]\n")
}
