// Classic algorithms, one file per topic: sorting.vs, searching.vs,
// numbers.vs, strings.vs, graph.vs, dp.vs, structures.vs. Every .vs in a
// directory shares one namespace, so main calls them directly.
use io

fun main() {
  io.println("== sorting")
  val data = [5, 2, 9, 1, 5, 6, 0, 3]
  io.println("bubble    ${bubbleSort(data)}")
  io.println("insertion ${insertionSort(data)}")
  io.println("selection ${selectionSort(data)}")
  io.println("merge     ${mergeSort(data)}")
  io.println("quick     ${quickSort(data)}")
  io.println("counting  ${countingSort(data, 9)}")
  io.println("heap      ${heapSort(data)}")
  io.println("words     ${insertionSort(["pear", "apple", "fig"])}")
  io.println("sorted? ${isSorted(data)} ${isSorted(mergeSort(data))}")

  io.println("== searching")
  val sorted = mergeSort(data)
  io.println("linear 9 at ${linearSearch(data, 9)}, 7 at ${linearSearch(data, 7)}")
  io.println("binary 6 at ${binarySearch(sorted, 6)}, 4 at ${binarySearch(sorted, 4)}")
  io.println("binaryRec 0 at ${binarySearchRec(sorted, 0, 0, sorted.len() - 1)}")
  io.println("lowerBound 4 -> ${lowerBound(sorted, 4)}, 100 -> ${lowerBound(sorted, 100)}")
  io.println("prelude on $sorted: 6 at ${sorted.binarySearch(6)}, 4 at ${sorted.binarySearch(4)}")
  io.println("prelude 5 occupies [${sorted.lowerBound(5)}, ${sorted.upperBound(5)})")
  io.println("partitionPoint x <= 5 -> ${sorted.partitionPoint(x => x <= 5)}")
  val names = ["apple", "fig", "pear"]
  io.println("binarySearchBy fig -> ${names.binarySearchBy(w => w, "fig")}, kiwi -> ${names.binarySearchBy(w => w, "kiwi")}")
  io.println("binarySearchWith, descending: ${[9, 6, 5, 1].binarySearchWith(x => (5).compareTo(x))}")
  io.println("the two implementations agree: ${preludeAgrees(data)}")
  io.println("pair summing to 11: ${pairWithSum(sorted, 11)}, to 100: ${pairWithSum(sorted, 100)}")

  io.println("== numbers")
  io.println("gcd(84, 36) = ${gcd(84, 36)}, lcm(4, 6) = ${lcm(4, 6)}")
  io.println("primes to 50: ${sieve(50)}")
  io.println("isPrime 97 ${isPrime(97)}, 91 ${isPrime(91)}")
  val memo: MutableMap<i64, i64> = [:]
  io.println("fib(30) = ${fib(30)} memo ${fibMemo(30, memo)} (table ${memo.len()} entries)")
  io.println("2^10 = ${power(2, 10)}, 3^13 mod 7 = ${powMod(3, 13, 7)}, 10! = ${factorial(10)}")
  io.println("digits(90210) = ${digits(90210)}, isqrt(99) = ${isqrt(99)}")
  io.println("360 = ${factorize(360)}")

  io.println("== strings")
  io.println("reverse ${reverse("héllo")}")
  io.println("palindrome ${isPalindrome("A man a plan a canal Panama")} ${isPalindrome("veles")}")
  io.println("anagram ${isAnagram("Listen", "Silent")} ${isAnagram("abc", "abd")}")
  io.println("counts ${wordCounts("the cat and the hat and the bat")}")
  io.println("rle ${runLengthEncode("aaabccdddd")}")
  io.println("caesar ${caesar("Hello, World!", 3)} -> ${caesar(caesar("Hello, World!", 3), -3)}")
  io.println("find naive ${findNaive("the quick brown fox", "brown")} kmp ${findKmp("the quick brown fox", "brown")} missing ${findKmp("abc", "zz")}")
  io.println("kmp aabaaab in aaabaabaaab: ${findKmp("aaabaabaaab", "aabaaab")}")
  io.println("prefix ${commonPrefix(["interstellar", "internet", "interval"])}")

  io.println("== graph")
  val g = Graph.withNodes(7)
  g.addUndirected(0, 1)
  g.addUndirected(0, 2)
  g.addUndirected(1, 3)
  g.addUndirected(2, 3)
  g.addUndirected(3, 4)
  g.addUndirected(5, 6)
  io.println("bfs ${g.bfs(0)}")
  io.println("dfs ${g.dfs(0)}")
  io.println("dist ${g.distances(0)}")
  io.println("components ${g.components()}")
  val dag = Graph.withNodes(6)
  dag.addEdge(5, 2)
  dag.addEdge(5, 0)
  dag.addEdge(4, 0)
  dag.addEdge(4, 1)
  dag.addEdge(2, 3)
  dag.addEdge(3, 1)
  io.println("topo ${dag.topologicalOrder()}")
  dag.addEdge(1, 5)
  io.println("topo with cycle ${dag.topologicalOrder()}")
  val edges = [(0, 1, 4), (0, 2, 1), (2, 1, 2), (1, 3, 1), (2, 3, 5)]
  io.println("dijkstra ${dijkstra(5, edges, 0)}")

  io.println("== dp")
  io.println("lcs ${lcsLength("ABCBDAB", "BDCABA")}")
  io.println("edit ${editDistance("kitten", "sitting")}")
  io.println("knapsack ${knapsack([1, 3, 4, 5], [1, 4, 5, 7], 7)}")
  io.println("coins ${coinChange([1, 2, 5], 11)} ${coinChange([2], 3)}")
  io.println("lis ${longestIncreasing([10, 9, 2, 5, 3, 7, 101, 18])}")
  io.println("kadane ${maxSubarraySum([-2, 1, -3, 4, -1, 2, 1, -5, 4])}")
  io.println("stairs ${climbStairs(10)}")

  io.println("== structures")
  val q = deque<string>()
  loop (s in ["a", "b", "c"]) q.addLast(s)
  q.addFirst("z")
  io.println("deque $q first ${q.removeFirst()} last ${q.removeLast()} -> $q len ${q.len()}")
  io.println("sliding max ${slidingMax([1, 3, -1, -3, 5, 3, 6, 7], 3)}")
  io.println("balanced ${balanced("{[()]}")} ${balanced("([)]")} ${balanced("((")}")
  var tree = Bst()
  loop (v in [50, 30, 70, 20, 40, 60, 80, 30]) tree.insert(v)
  io.println("bst ${tree.inOrder()} size ${tree.size} height ${tree.height()} min ${tree.min()} max ${tree.max()}")
  io.println("bst has 60 ${tree.contains(60)}, 65 ${tree.contains(65)}")
  val heap = MinHeap()
  loop (x in [7, 3, 9, 1, 4]) heap.push(x)
  io.println("heap peek ${heap.peek()} pop ${heap.pop()} ${heap.pop()} len ${heap.len()}")
  val words = priorityQueue<string>()
  loop (w in ["pear", "apple", "fig"]) words.push(w)
  io.println("priority ${words.pop()} ${words.pop()} ${words.pop()} ${words.pop()}")
}
